🚸 Verbose auth and duplicate error message in add to bookmark
likecoin/likecoin-app pull request #228
Opened 2020-09-29 09:41 UTC by williamchong

API should return 401 on auth and 409 on duplicate bookmark
Currently it returns 500 on duplicate, [PR](https://github.com/likecoin/liker-land/pull/299) pending for the latter behaviour

2020-09-29 10:11 UTC, nwingt requested changes

2020-09-29 10:11 UTC, nwingt commented on app/services/api/api-problem.ts
> +  /**
Seems redundant

2020-09-29 10:24 UTC, nwingt approved these changes

2020-09-30 03:00 UTC, nnkken approved these changes

2020-10-08 03:26 UTC, merged