Update zh-Hant-TW.json
likecoin/likecoin-app pull request #239
Opened 2021-01-03 15:02 UTC by chiyi4488

### 更新大方向：

1. 香港口語文字，改為台灣本地化翻譯。
2. 統一設定頁面的標題、進入設定頁面的按紐。
3. 大陸 or 香港用字改為台灣用字，例如 `轉賬 to 轉帳、兼容 to 相容、鏈結 to 連結`。
4. `你` to `您`。
5. 行 29：原 `ok:好`，改為 `ok:確定`。（按MS標準）
6. 部分標點符號從半形 to 全形。
7. 刪除贅字，例如行121 `暫時沒有通知`，改為 `沒有通知`。（參考其他軟體本地化翻譯作法）
8. 盡量統一有 `沒有` and `尚未` 字串的用法。
9. `按` to `點`（`點`感覺比較直觀，也統一翻譯用法）

### 需特別注意、審核的地方：

行300 "com.oice.membership"，由於我不熟悉 oice membership 的服務，不確定是否有改錯。

2021-02-08 02:01 UTC, nwingt approved these changes

2021-02-08 02:02 UTC, nwingt commented
@ckxpress Please review

2021-03-03 09:28 UTC, nwingt commented
@shellyYG @WeiJun0827 Please review when you are free =)

2021-03-03 09:44 UTC, WeiJun0827 commented on app/i18n/translations/zh-Hant-TW.json
>      "Yesterday": "昨日"
這邊我覺得可以用 昨天

2021-03-03 09:49 UTC, WeiJun0827 commented on app/i18n/translations/zh-Hant-TW.json
> +    "emptyLabel": "瀏覽頭條時，點書籤圖標，可把作品加入閱讀列表，方便往後細閱。",
點 可以用 點選 會比較口語
方便往後細閱 也許可以考慮用 方便稍後閱讀 (參考facebook珍藏項目功能說明)

2021-03-03 09:49 UTC, shellyYG reviewed
%{from} 讚賞“了”您的作品，您獲得 %{amount}。 （加一個“了”會比較好）
%{from} Super Liked 您的作品，您獲得 %{amount}。（like--> liked)
今天有 %{likers} 讚賞了您的作品，您共獲得 %{amount}。(加一個“了”會比較好）
讓對方追蹤自己的 Super Like...這句話怪怪的，讓對方追蹤自己，成為自己的 Super Like？
於頂部選取您的--> 於最上方選取您的
您最近曾轉移委託至這驗證人--> 您最近曾轉移委託至”此“驗證人
"正在登入" 應維持 "正在登入“（媒體登入有點怪 ... 媒體是 media的意思）

2021-03-04 09:49 UTC, chiyi4488 commented on app/i18n/translations/zh-Hant-TW.json
>      "Yesterday": "昨日"
我認為確實可以這樣變更，我要直接修改還是再Pull request?

2021-03-04 10:08 UTC, chiyi4488 commented
@shellyYG

- [x]  %{from} 讚賞“了”您的作品，您獲得 %{amount}。 （加一個“了”會比較好）
- [x]  %{from} Super Liked 您的作品，您獲得 %{amount}。（like--> liked)
- [x]  今天有 %{likers} 讚賞了您的作品，您共獲得 %{amount}。(加一個“了”會比較好）
- [x]  讓對方追蹤自己的 Super Like...這句話怪怪的，讓對方追蹤自己，成為自己的 Super Like？
- [x]  於頂部選取您的--> 於最上方選取您的
- [x]  您最近曾轉移委託至這驗證人--> 您最近曾轉移委託至”此“驗證人
- [x]  "正在登入" 應維持 "正在登入“（媒體登入有點怪 ... 媒體是 media的意思）

謝謝你告訴我這個「**正在登入**」字串的問題，因為這樣我默默發現我沒有統整「**正在登入**」&「**媒體登入**」，剛剛已把「**網站登入**」改成「**媒體登入**」。
而「正在登入」這個字串，我改成媒體登入的原因是，個人感覺寫「正在」，很像是系統在進行什麼後台操作，所以改成「**媒體登入**」，把該訊息窗口變成是"媒體登入"的說明的感覺。
也的確，「**媒體登入**」的譯詞已經偏離原意，所以我剛剛改回了「**正在登入**」。(我覺得可以討論，從原文改😅)

2021-03-26 07:41 UTC, shellyYG commented
您可以從閱讀列表中封存文章 --> 從閱讀列表中把文章歸檔
分享您的推薦連結給朋友，大家同獲奬賞，同時成為對方的內容伯樂，讓對方成為自己的 Super Like。趕快邀請朋友下載 Liker Land 吧！“--> 分享您的推薦連結給朋友，一起獲得奬賞，同時成為對方的內容伯樂，讓對方成為自己的 Super Liker。現在就邀請朋友下載 Liker Land 吧！“,

2021-03-26 08:08 UTC, shellyYG requested changes

2021-03-26 08:08 UTC, shellyYG commented on app/i18n/translations/zh-Hant-TW.json
> +    "DescriptionLabel": "分享您的推薦連結給朋友，大家同獲奬賞，同時成為對方的內容伯樂，讓對方成為自己的 Super Like。趕快邀請朋友下載 Liker Land 吧！",
分享您的推薦連結給朋友，大家同獲奬賞，同時成為對方的內容伯樂，讓對方成為自己的 Super Like。趕快邀請朋友下載 Liker Land 吧！“--> 分享您的推薦連結給朋友，一起獲得奬賞，同時成為對方的內容伯樂，讓對方成為自己的 Super Liker。現在就邀請朋友下載 Liker Land 吧！“,

2021-03-30 06:47 UTC, merged

2021-03-30 06:47 UTC, williamchong commented
@chiyi4488 Sorry for the late merge and thank you for contribution

2021-03-30 11:43 UTC, chiyi4488 commented on app/i18n/translations/zh-Hant-TW.json
> +    "DescriptionLabel": "分享您的推薦連結給朋友，大家同獲奬賞，同時成為對方的內容伯樂，讓對方成為自己的 Super Like。趕快邀請朋友下載 Liker Land 吧！",
因為在段考前夕，所以都沒有回覆，十分抱歉。這個本地化建議我會在下次請求時修整（如果有下一次的話）😅