Support Wallet Connect
likecoin/likecoin-app pull request #293
Opened 2021-11-22 06:07 UTC by nwingt

2021-11-29 20:02 UTC, williamchong requested changes
We did not use any bridge, or hook into custom walletconnect protocol like `keplr://` right?

2021-11-29 20:02 UTC, williamchong commented on app/models/wallet-connect-client/wallet-connect-client.ts
> +
Please wrap the cases in `{}`s, and comment what do the `params` mean in each case if possible

2021-11-29 20:02 UTC, williamchong commented on app/models/wallet-connect-client/wallet-connect-client.ts
> +      console.log("handleCallRequestApproval", payload, result)
Please remove console.log

2021-12-03 03:03 UTC, nwingt commented on app/models/wallet-connect-client/wallet-connect-client.ts
> +      const { peerId, peerMeta } = payload.params[0]
Params are returned in an array and we just need the first param

2021-12-03 03:05 UTC, nwingt commented on app/screens/wallet-connect-request-screen/wallet-connect-request-screen.tsx
> +  peerMeta: any;
Reserve for showing the content of peerMeta in UI in the future

2022-02-23 13:06 UTC, merged