🐛 Fix limit to 100 validators
likecoin/likecoin-app pull request #302
Opened 2022-02-25 08:46 UTC by nwingt

2022-03-06 15:32 UTC, AuroraHuang22 approved these changes

2022-03-20 19:48 UTC, williamchong requested changes

2022-03-20 19:48 UTC, williamchong commented on app/services/cosmos/cosmos.ts
> +    const { validators, pagination } = await this.queryClient.staking.validators(bondStatus, paginationKey)
might have off by one issue since https://github.com/cosmos/cosmos-sdk/pull/11408
need to mitigate with `0x0` next_key for first query

2022-03-20 19:48 UTC, williamchong commented on app/i18n/translations/en.json
> +  "civic_liker_v3_summary_status_activating": "About to active",
```suggestion
  "civic_liker_v3_summary_status_activating": "About to activate",
```

2022-03-25 15:08 UTC, merged