🐛 Resolve issues of WalletConnect
likecoin/likecoin-app pull request #355
Opened 2023-04-24 06:14 UTC by nwingt

### Added button to disconnect all WC sessions
<img width="336" alt="image" src="https://user-images.githubusercontent.com/17264716/233913672-87bed9da-0d8b-47b6-9c5f-0ef47e3bf89e.png">
<img width="335" alt="image" src="https://user-images.githubusercontent.com/17264716/233913905-c7106e71-1a6c-4646-a16d-29b55f9eba04.png">

2023-04-24 09:31 UTC, williamchong requested changes

2023-04-25 01:20 UTC, williamchong approved these changes
斷開 can be used in cn though

2023-04-25 01:23 UTC, nwingt commented
@williamchong Keep 断开

2023-04-25 01:24 UTC, williamchong approved these changes

2023-04-25 01:25 UTC, merged